/**
 * FOUNDATION — color.
 *
 * Material 3 role model, shadcn semantic compatibility, Tailwind v4-ready.
 *
 * Owns: palette families, role/tone policy, pairing, dynamic/static eligibility.
 * Does not own: literal colors (tokens.json), HCT generation, Tailwind projection,
 * or component variants.
 */

import { definePolicy } from './contract.mjs'
import { deepFreeze } from './shared.mjs'

export const COLOR_MODES = deepFreeze(['light', 'dark'])

/* --------------------------------------------------------------- palettes -- */

/**
 * Values live in tokens.json. These are references only.
 *
 * scheme families may be regenerated by Material Color Utilities in dynamic mode.
 * static families retain product meaning regardless of the dynamic source.
 */
export const COLOR_PALETTES = deepFreeze({
  error: { seed: 'color.seed.error', source: 'static' },
  info: { seed: 'color.seed.info', source: 'static' },
  neutral: { seed: 'color.seed.neutral', source: 'scheme' },
  'neutral-variant': { seed: 'color.seed.neutral-variant', source: 'scheme' },
  primary: { seed: 'color.seed.primary', source: 'scheme' },
  secondary: { seed: 'color.seed.secondary', source: 'scheme' },
  statutory: { seed: 'color.seed.statutory', source: 'static' },
  success: { seed: 'color.seed.success', source: 'static' },
  tertiary: { seed: 'color.seed.tertiary', source: 'scheme' },
  warning: { seed: 'color.seed.warning', source: 'static' },
})

export const COLOR_SCHEMES = deepFreeze({
  dynamic: {
    dynamicFamilies: ['primary', 'secondary', 'tertiary', 'neutral', 'neutral-variant'],
    lockedFamilies: ['error', 'success', 'warning', 'info', 'statutory'],
  },
  static: {
    dynamicFamilies: [],
    lockedFamilies: Object.keys(COLOR_PALETTES),
  },
})

/* ------------------------------------------------------------------ kinds -- */

export const COLOR_KINDS = deepFreeze({
  compositing: { alpha: true, mode: 'exempt' },
  decorative: { alpha: false, mode: 'exempt' },
  surface: { alpha: false, mode: 'surface' },
  text: { alpha: false, contrast: 'text', mode: 'measures' },
  ui: { alpha: false, contrast: 'ui', mode: 'measures' },
})

const KIND_MODES = deepFreeze(['surface', 'measures', 'exempt'])

/* --------------------------------------------------------------- contexts -- */

export const COLOR_CONTEXTS = deepFreeze([
  'surface',
  'surface-variant',
  'inverse-surface',

  'primary',
  'primary-container',
  'secondary',
  'secondary-container',
  'tertiary',
  'tertiary-container',

  'error',
  'error-container',
  'success',
  'success-container',
  'warning',
  'warning-container',
  'info',
  'info-container',
  'statutory',
  'statutory-container',
])

/* ---------------------------------------------------------- baseline tones -- */

/**
 * Current Material 3 baseline tone relationships.
 *
 * These are the STATIC baseline. A Material dynamic scheme may move tones for
 * contrast while keeping exactly the same role vocabulary.
 *
 * Surface containers are tone-based surfaces, not opacity overlays.
 */
export const M3_TONES = deepFreeze({
  error: ['error', 40, 80],
  'error-container': ['error', 90, 30],
  'inverse-on-surface': ['neutral', 95, 20],
  'inverse-primary': ['primary', 80, 40],

  'inverse-surface': ['neutral', 20, 90],
  'on-error': ['error', 100, 20],
  'on-error-container': ['error', 10, 90],
  'on-primary': ['primary', 100, 20],
  'on-primary-container': ['primary', 10, 90],
  'on-secondary': ['secondary', 100, 20],
  'on-secondary-container': ['secondary', 10, 90],
  'on-surface': ['neutral', 10, 90],
  'on-surface-variant': ['neutral-variant', 30, 80],
  'on-tertiary': ['tertiary', 100, 20],
  'on-tertiary-container': ['tertiary', 10, 90],
  outline: ['neutral-variant', 50, 60],
  'outline-variant': ['neutral-variant', 80, 30],
  primary: ['primary', 40, 80],
  'primary-container': ['primary', 90, 30],
  scrim: ['neutral', 0, 0],

  secondary: ['secondary', 40, 80],
  'secondary-container': ['secondary', 90, 30],

  shadow: ['neutral', 0, 0],

  surface: ['neutral', 99, 10],
  'surface-bright': ['neutral', 98, 24],
  'surface-container': ['neutral', 94, 12],
  'surface-container-high': ['neutral', 92, 17],
  'surface-container-highest': ['neutral', 90, 22],
  'surface-container-low': ['neutral', 96, 10],
  'surface-container-lowest': ['neutral', 100, 4],
  'surface-dim': ['neutral', 87, 6],

  'surface-variant': ['neutral-variant', 90, 30],

  tertiary: ['tertiary', 40, 80],
  'tertiary-container': ['tertiary', 90, 30],
})

/**
 * Product status families copy M3's strong / on / container / on-container
 * grammar. Their palettes are intentionally static.
 */
const statusTones = (palette) => ({
  [palette]: [palette, 40, 80],
  [`on-${palette}`]: [palette, 100, 20],
  [`${palette}-container`]: [palette, 90, 30],
  [`on-${palette}-container`]: [palette, 10, 90],
})

export const STATUS_TONES = deepFreeze({
  ...statusTones('success'),
  ...statusTones('warning'),
  ...statusTones('info'),
  ...statusTones('statutory'),
})

export const COLOR_TONES = deepFreeze({
  ...M3_TONES,
  ...STATUS_TONES,
})

export function toneDefinition(role, registry = COLOR_TONES) {
  const value = registry[role]
  if (!value) {
    throw new Error(`no tone definition for color role '${role}'`)
  }
  const [palette, light, dark] = value
  return { dark, light, palette }
}

/* ----------------------------------------------------------- semantic roles -- */

/**
 * Surface roles PROVIDE contexts.
 * Foreground/UI roles CONSUME contexts.
 * Pairing is derived rather than manually enumerated.
 */
export const COLOR_ROLES = deepFreeze({
  error: { kind: 'surface', provides: ['error'] },
  'error-container': { kind: 'surface', provides: ['error-container'] },

  info: { kind: 'surface', provides: ['info'] },
  'info-container': { kind: 'surface', provides: ['info-container'] },
  'inverse-on-surface': { against: ['inverse-surface'], kind: 'text' },
  'inverse-primary': {
    kind: 'decorative',
    reason: 'accent on an inverse surface; final pairing belongs to its consumer',
  },

  'inverse-surface': { kind: 'surface', provides: ['inverse-surface'] },
  'on-error': { against: ['error'], kind: 'text' },
  'on-error-container': { against: ['error-container'], kind: 'text' },
  'on-info': { against: ['info'], kind: 'text' },
  'on-info-container': { against: ['info-container'], kind: 'text' },
  'on-primary': { against: ['primary'], kind: 'text' },
  'on-primary-container': { against: ['primary-container'], kind: 'text' },
  'on-secondary': { against: ['secondary'], kind: 'text' },
  'on-secondary-container': { against: ['secondary-container'], kind: 'text' },
  'on-statutory': { against: ['statutory'], kind: 'text' },
  'on-statutory-container': { against: ['statutory-container'], kind: 'text' },
  'on-success': { against: ['success'], kind: 'text' },
  'on-success-container': { against: ['success-container'], kind: 'text' },
  'on-surface': { against: ['surface'], kind: 'text' },
  'on-surface-variant': { against: ['surface-variant'], kind: 'text' },
  'on-tertiary': { against: ['tertiary'], kind: 'text' },
  'on-tertiary-container': { against: ['tertiary-container'], kind: 'text' },
  'on-warning': { against: ['warning'], kind: 'text' },
  'on-warning-container': { against: ['warning-container'], kind: 'text' },

  outline: { against: ['surface'], kind: 'ui' },
  'outline-variant': {
    kind: 'decorative',
    reason: 'low-emphasis divider, not a sole interactive boundary',
  },
  primary: { kind: 'surface', provides: ['primary'] },
  'primary-container': { kind: 'surface', provides: ['primary-container'] },
  scrim: {
    kind: 'compositing',
    reason: 'scrim is composited over arbitrary content',
  },

  secondary: { kind: 'surface', provides: ['secondary'] },
  'secondary-container': { kind: 'surface', provides: ['secondary-container'] },

  shadow: {
    kind: 'compositing',
    reason: 'shadow ink is composited at render',
  },

  statutory: { kind: 'surface', provides: ['statutory'] },
  'statutory-container': { kind: 'surface', provides: ['statutory-container'] },

  success: { kind: 'surface', provides: ['success'] },
  'success-container': { kind: 'surface', provides: ['success-container'] },

  surface: { kind: 'surface', provides: ['surface'] },
  'surface-bright': { kind: 'surface', provides: ['surface'] },
  'surface-container': { kind: 'surface', provides: ['surface'] },
  'surface-container-high': { kind: 'surface', provides: ['surface'] },
  'surface-container-highest': { kind: 'surface', provides: ['surface'] },
  'surface-container-low': { kind: 'surface', provides: ['surface'] },
  'surface-container-lowest': { kind: 'surface', provides: ['surface'] },
  'surface-dim': { kind: 'surface', provides: ['surface'] },

  'surface-variant': { kind: 'surface', provides: ['surface-variant'] },

  tertiary: { kind: 'surface', provides: ['tertiary'] },
  'tertiary-container': { kind: 'surface', provides: ['tertiary-container'] },

  warning: { kind: 'surface', provides: ['warning'] },
  'warning-container': { kind: 'surface', provides: ['warning-container'] },
})

/* ------------------------------------------------------------- shadcn bridge -- */

/**
 * shadcn names are aliases onto the governed M3-style semantic scheme.
 * tailwind.mjs projects them into Tailwind v4's --color-* namespace.
 */
export const SHADCN_COLOR_BINDINGS = deepFreeze({
  // shadcn accent is interactive hover/selection emphasis, not tertiary brand color.
  accent: 'primary-container',
  'accent-foreground': 'on-primary-container',
  background: 'surface',

  border: 'outline-variant',

  card: 'surface-container-low',
  'card-foreground': 'on-surface',

  destructive: 'error',
  'destructive-foreground': 'on-error',
  foreground: 'on-surface',
  input: 'outline',

  muted: 'surface-container',
  'muted-foreground': 'on-surface-variant',
  popover: 'surface-container-high',
  'popover-foreground': 'on-surface',

  primary: 'primary',
  'primary-foreground': 'on-primary',
  ring: 'primary',

  // shadcn secondary is lower-emphasis filled UI.
  secondary: 'secondary-container',
  'secondary-foreground': 'on-secondary-container',

  sidebar: 'surface-container-low',
  'sidebar-accent': 'secondary-container',
  'sidebar-accent-foreground': 'on-secondary-container',
  'sidebar-border': 'outline-variant',
  'sidebar-foreground': 'on-surface',
  'sidebar-primary': 'primary',
  'sidebar-primary-foreground': 'on-primary',
  'sidebar-ring': 'primary',
})

/* ------------------------------------------------------ M3 tone-pair guards -- */

/**
 * Material's accessible-tone examples:
 *   T50 ↔ T98 > 3:1
 *   T30 ↔ T98 > 7:1
 *
 * These demonstrate tone separation; they do not replace M3's baseline role tones.
 */
export const ACCESSIBLE_TONE_PAIRS = deepFreeze({
  high: { background: 98, foreground: 30, minimum: 7 },
  standard: { background: 98, foreground: 50, minimum: 3 },
})

const luminanceFromTone = (tone) => {
  if (!Number.isFinite(tone) || tone < 0 || tone > 100) {
    throw new Error(`tone must be in [0, 100], received ${tone}`)
  }
  const f = (tone + 16) / 116
  return tone > 8 ? f ** 3 : tone / 903.296_296_2
}

export function contrastRatioOfTones(a, b) {
  const x = luminanceFromTone(a)
  const y = luminanceFromTone(b)
  return (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05)
}

/* --------------------------------------------------------------- pairing -- */

export function pairsFor(role, roles = COLOR_ROLES, kinds = COLOR_KINDS) {
  const policy = roles[role]
  if (!policy) {
    throw new Error(`no color role '${role}'`)
  }

  const kind = kinds[policy.kind]
  if (!kind) {
    throw new Error(`color role '${role}' names unknown kind '${policy.kind}'`)
  }
  if (kind.mode !== 'measures') {
    return []
  }

  const wanted = new Set(policy.against ?? [])
  return Object.entries(roles)
    .filter(
      ([name, other]) =>
        name !== role && (other.provides ?? []).some((context) => wanted.has(context)),
    )
    .map(([name]) => name)
    .sort((a, b) => a.localeCompare(b))
}

/* ------------------------------------------------------------- assertions -- */

const ROLE_FIELDS = deepFreeze(['against', 'kind', 'provides', 'reason'])

export function assertColorKinds(kinds = COLOR_KINDS) {
  for (const [name, kind] of Object.entries(kinds)) {
    if (!KIND_MODES.includes(kind.mode)) {
      throw new Error(`color kind '${name}' has unknown mode '${kind.mode}'`)
    }
    if (typeof kind.alpha !== 'boolean') {
      throw new Error(`color kind '${name}' does not state alpha permission`)
    }
    if (kind.mode === 'measures') {
      if (!kind.contrast) {
        throw new Error(`color kind '${name}' measures but names no contrast class`)
      }
      if (kind.alpha) {
        throw new Error(`color kind '${name}' measures contrast and permits alpha`)
      }
    } else if ('contrast' in kind) {
      throw new Error(`color kind '${name}' does not measure but names a contrast class`)
    }
  }
  return kinds
}

export function assertPalettes(palettes = COLOR_PALETTES, schemes = COLOR_SCHEMES) {
  const names = Object.keys(palettes)
  for (const [name, palette] of Object.entries(palettes)) {
    if (!/^color\.seed\.[a-z0-9-]+$/.test(palette.seed)) {
      throw new Error(`palette '${name}' must reference color.seed.*, received '${palette.seed}'`)
    }
    if (!['scheme', 'static'].includes(palette.source)) {
      throw new Error(`palette '${name}' has unknown source '${palette.source}'`)
    }
  }

  for (const [scheme, policy] of Object.entries(schemes)) {
    const declared = [...policy.dynamicFamilies, ...policy.lockedFamilies]
    if (new Set(declared).size !== declared.length) {
      throw new Error(`color scheme '${scheme}' both changes and locks a palette family`)
    }
    for (const name of names) {
      if (!declared.includes(name)) {
        throw new Error(`color scheme '${scheme}' does not classify palette '${name}'`)
      }
    }
  }
  return palettes
}

export function assertColorTones(tones = COLOR_TONES, palettes = COLOR_PALETTES) {
  for (const [role, raw] of Object.entries(tones)) {
    if (!Array.isArray(raw) || raw.length !== 3) {
      throw new Error(`tone role '${role}' must be [palette, light, dark]`)
    }
    const [palette, light, dark] = raw
    if (!palettes[palette]) {
      throw new Error(`tone role '${role}' names unknown palette '${palette}'`)
    }
    for (const [mode, tone] of [
      ['light', light],
      ['dark', dark],
    ]) {
      if (!Number.isFinite(tone) || tone < 0 || tone > 100) {
        throw new Error(`tone role '${role}' has invalid ${mode} tone '${tone}'`)
      }
    }
  }
  return tones
}

const assertContextList = (role, field, value) => {
  if (value === undefined) {
    return
  }
  if (!Array.isArray(value) || value.length === 0) {
    throw new Error(`color role '${role}' ${field} must be a non-empty array`)
  }
  if (new Set(value).size !== value.length) {
    throw new Error(`color role '${role}' repeats a context in ${field}`)
  }
  for (const context of value) {
    if (!COLOR_CONTEXTS.includes(context)) {
      throw new Error(`color role '${role}' names unknown context '${context}'`)
    }
  }
}

export function assertColorRoles(roles = COLOR_ROLES, kinds = COLOR_KINDS, tones = COLOR_TONES) {
  if (Object.keys(roles).length === 0) {
    throw new Error('color role registry is empty -- zero roles govern nothing')
  }

  for (const [role, policy] of Object.entries(roles)) {
    if (!tones[role]) {
      throw new Error(`color role '${role}' has no tone definition`)
    }

    for (const field of Object.keys(policy)) {
      if (!ROLE_FIELDS.includes(field)) {
        throw new Error(`color role '${role}' declares unknown field '${field}'`)
      }
    }

    const kind = kinds[policy.kind]
    if (!kind) {
      throw new Error(`color role '${role}' names unknown kind '${policy.kind}'`)
    }

    assertContextList(role, 'against', policy.against)
    assertContextList(role, 'provides', policy.provides)

    if (kind.mode === 'measures') {
      if ((policy.against ?? []).length === 0) {
        throw new Error(`color role '${role}' measures but consumes no context`)
      }
      if (pairsFor(role, roles, kinds).length === 0) {
        throw new Error(`color role '${role}' measures but derives no pair`)
      }
    }

    if (kind.mode === 'surface' && (policy.provides ?? []).length === 0) {
      throw new Error(`color role '${role}' is a surface but provides no context`)
    }

    if (kind.mode === 'exempt') {
      if (policy.against || policy.provides) {
        throw new Error(`color role '${role}' is exempt but declares composition contexts`)
      }
      if (typeof policy.reason !== 'string' || policy.reason.trim() === '') {
        throw new Error(`color role '${role}' is exempt and must state why`)
      }
    }
  }

  const provided = new Set()
  const consumed = new Set()
  for (const policy of Object.values(roles)) {
    for (const x of policy.provides ?? []) {
      provided.add(x)
    }
    for (const x of policy.against ?? []) {
      consumed.add(x)
    }
  }
  for (const x of consumed) {
    if (!provided.has(x)) {
      throw new Error(`color context '${x}' is consumed but not provided`)
    }
  }
  for (const x of provided) {
    if (!consumed.has(x)) {
      throw new Error(`color context '${x}' is provided but not consumed`)
    }
  }

  return roles
}

export function assertShadcnBindings(bindings = SHADCN_COLOR_BINDINGS, roles = COLOR_ROLES) {
  for (const [name, role] of Object.entries(bindings)) {
    if (!roles[role]) {
      throw new Error(`shadcn color '${name}' binds to unknown role '${role}'`)
    }
  }
  return bindings
}

export function assertAccessibleTonePairs(pairs = ACCESSIBLE_TONE_PAIRS) {
  for (const [name, pair] of Object.entries(pairs)) {
    const ratio = contrastRatioOfTones(pair.foreground, pair.background)
    if (ratio < pair.minimum) {
      throw new Error(
        `tone pair '${name}' is ${ratio.toFixed(2)}:1 for T${pair.foreground}/T${pair.background}, ` +
          `below ${pair.minimum}:1`,
      )
    }
  }
  return pairs
}

/* --------------------------------------------------------------- policy -- */

export function assertColorPolicy() {
  assertColorKinds()
  assertPalettes()
  assertColorTones()
  assertColorRoles()
  assertShadcnBindings()
  assertAccessibleTonePairs()
  return COLOR_ROLES
}

export const colorPolicy = definePolicy({
  assert: assertColorPolicy,
  id: 'foundation.color',
  kind: 'foundation',
})
