import type { Meta, StoryObj } from '@storybook/react-vite'
import { FIELD_SPAN, Field } from '@xforge/design/components/field'
import { Grid } from '@xforge/design/components/grid'
import { Stack } from '@xforge/design/components/stack'
import { TextInput } from '@xforge/design/components/text-input'

/**
 * Field is the only authored component that names something it rendered BY
 * REFERENCE — the label's `for`, the control's `aria-describedby`. Those ids
 * are generated by Base UI and never appear in a story, which is the point: a
 * screen that had to write them would eventually write two the same.
 *
 * The states worth looking at are the ones a form is in most of the time, not
 * the empty one: described, invalid, and described AND invalid together.
 */

const meta = {
  args: { label: 'Job title' },
  component: Field,
  title: 'Design/Field',
} satisfies Meta<typeof Field>

export default meta
type Story = StoryObj<typeof meta>

export const Playground: Story = {
  args: {
    children: <TextInput placeholder="Payroll Manager" />,
    label: 'Job title',
  },
}

/** A hint that says what to enter, before anyone has entered anything. */
export const Described: Story = {
  args: {
    children: <TextInput placeholder="MY-0001" />,
    description: 'Unique within the employer, not across the group.',
    label: 'Employee number',
  },
}

/**
 * BOTH AT ONCE, which is the state a single `helperText` prop cannot express.
 * The description does not disappear when the error arrives: the rule and the
 * complaint are different sentences, and the person needs the rule most at the
 * moment they have broken it.
 */
export const DescribedAndInvalid: Story = {
  args: {
    children: <TextInput defaultValue="MY-0001" />,
    description: 'Unique within the employer, not across the group.',
    error: 'MY-0001 already belongs to Siti binti Rahman at this employer.',
    label: 'Employee number',
  },
}

/**
 * The error is a SERVER's word here, not the platform's. "Already belongs to
 * someone" is not expressible as an HTML constraint, which is why the Field is
 * told it is invalid rather than asked.
 */
export const Invalid: Story = {
  args: {
    children: <TextInput defaultValue="" />,
    error: 'A job title is required for an employment period.',
    label: 'Job title',
  },
}

export const Disabled: Story = {
  args: {
    children: <TextInput defaultValue="Payroll Manager" />,
    description: 'Set by the employment period; change it there.',
    disabled: true,
    label: 'Job title',
  },
}

/** Several fields together — the shape every command surface in this product will take. */
export const InAForm: Story = {
  args: { children: null, label: '' },
  render: () => (
    <Stack gap="normal">
      <Field label="Full name">
        <TextInput autoComplete="name" placeholder="Siti binti Rahman" />
      </Field>
      <Field
        description="Unique within the employer, not across the group."
        label="Employee number"
      >
        <TextInput placeholder="MY-0001" />
      </Field>
      <Field description="What this person is called, if it differs." label="Preferred name">
        <TextInput placeholder="Siti" />
      </Field>
    </Stack>
  ),
}

const SPANS = Object.keys(FIELD_SPAN).map(Number) as (keyof typeof FIELD_SPAN)[]

/**
 * EVERY SPAN, DERIVED FROM THE TABLE. Adding a fifth span makes this story frame it
 * without an edit, which is the reason the table is exported rather than re-typed here.
 *
 * Four tracks, and each field takes a different number of them — the mixed-width row a
 * `Grid` of equal columns cannot express and every real form needs.
 */
export const EverySpan: Story = {
  args: { children: null, label: '' },
  render: () => (
    <Grid columns={4} gap="normal">
      {SPANS.map((span) => (
        <Field key={span} label={`Spans ${span}`} span={span}>
          <TextInput aria-label={`Spans ${span}`} placeholder={`col-span-${span}`} />
        </Field>
      ))}
    </Grid>
  ),
}

/**
 * The row this was taken for: an employee number is short and a full name is long, so a
 * stack of full-width controls wastes the line and a grid of equal columns misreads it.
 */
export const AMixedWidthRow: Story = {
  args: { children: null, label: '' },
  render: () => (
    <Grid columns={4} gap="normal">
      <Field description="Unique within the employer." label="Employee number" span={1}>
        <TextInput placeholder="MY-0001" />
      </Field>
      <Field label="Full name" span={3}>
        <TextInput autoComplete="name" placeholder="Siti binti Rahman" />
      </Field>
      <Field label="Job title" span={2}>
        <TextInput placeholder="Payroll Manager" />
      </Field>
      <Field description="The first day of the period." label="Effective from" span={2}>
        <TextInput placeholder="2026-03-16" />
      </Field>
    </Grid>
  ),
}
